twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        uploadsPath: '%uploads_path%'
        uploadsDirectory: '%uploads_directory%'

when@test:
    twig:
        strict_variables: true
